/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "CPU:": {                                        "en": "CPU",                                             "de": "CPU",                                             "ru": "Процессор",                                       "pt": "CPU",                                             "nl": "CPU",                                             "fr": "CPU",                                             "it": "processore",                                      "es": "UPC",                                             "pl": "procesor",                                        "zh-cn": "CPU"},
    "Enabled": {                                     "en": "Enabled",                                         "de": "Aktiv",                                           "ru": "Активен",                                         "pt": "ativado",                                         "nl": "Ingeschakeld",                                    "fr": "Activée",                                         "it": "Abilitato",                                       "es": "Habilitado",                                      "pl": "Włączone",                                        "zh-cn": "启用"},
    "GPIOs": {                                       "en": "GPIOs",                                           "de": "GPIOs",                                           "ru": "GPIO Порты",                                      "pt": "GPIOs",                                           "nl": "GPIOs",                                           "fr": "GPIO",                                            "it": "GPIO",                                            "es": "GPIOs",                                           "pl": "GPIOs",                                           "zh-cn": "Gpio"},
    "Memory:": {                                     "en": "Memory",                                          "de": "Speicher",                                        "ru": "Память",                                          "pt": "Memória",                                         "nl": "Geheugen",                                        "fr": "Mémoire",                                         "it": "Memoria",                                         "es": "Memoria",                                         "pl": "Pamięć",                                          "zh-cn": "存储器"},
    "Network:": {                                    "en": "Network",                                         "de": "Network",                                         "ru": "Сеть",                                            "pt": "Rede",                                            "nl": "Netwerk",                                         "fr": "Réseau",                                          "it": "Rete",                                            "es": "Red",                                             "pl": "Sieć",                                            "zh-cn": "网络"},
    "Poll": {                                        "en": "Poll",                                            "de": "Pollen",                                          "ru": "Опрашивать",                                      "pt": "Votação",                                         "nl": "poll",                                            "fr": "Sondage",                                         "it": "Sondaggio",                                       "es": "Encuesta",                                        "pl": "Głosowanie",                                      "zh-cn": "民意调查"},
    "Port": {                                        "en": "Port",                                            "de": "Port",                                            "ru": "Порт",                                            "pt": "Porta",                                           "nl": "Haven",                                           "fr": "Port",                                            "it": "Porta",                                           "es": "Puerto",                                          "pl": "Port",                                            "zh-cn": "口"},
    "RPI-Monitor Adapter settings": {                "en": "RPI-Monitor Adapter settings",                    "de": "RPI-Monitor Adapter-Einstellungen",               "ru": "Настройки RPI-монитор адаптера",                  "pt": "Configurações do adaptador RPI-Monitor",          "nl": "RPI-Monitor Adapter-instellingen",                "fr": "Paramètres de l'adaptateur RPI-Monitor",          "it": "Impostazioni dell'adattatore monitor RPI",        "es": "Configuración del adaptador RPI-Monitor",         "pl": "Ustawienia adaptera RPI-Monitor",                 "zh-cn": "RPI-监视器的设置"},
    "Raspberry:": {                                  "en": "Raspberry",                                       "de": "Raspberry",                                       "ru": "Raspberry",                                       "pt": "Framboesa",                                       "nl": "Framboos",                                        "fr": "Framboise",                                       "it": "Lampone",                                         "es": "Frambuesa",                                       "pl": "Malina",                                          "zh-cn": "树莓"},
    "SDCard:": {                                     "en": "SD Card",                                         "de": "SD Karte",                                        "ru": "SD Карта",                                        "pt": "Cartão SD",                                       "nl": "SD-kaart",                                        "fr": "Carte SD",                                        "it": "Scheda SD",                                       "es": "Tarjeta SD",                                      "pl": "Karta SD",                                        "zh-cn": "SD卡"},
    "Swap:": {                                       "en": "Swap",                                            "de": "Swap",                                            "ru": "Swap",                                            "pt": "Troca",                                           "nl": "ruil",                                            "fr": "Échanger",                                        "it": "Scambiare",                                       "es": "Intercambiar",                                    "pl": "Zamiana",                                         "zh-cn": "交换"},
    "Temperature:": {                                "en": "Temperature",                                     "de": "Temperatur",                                      "ru": "Температура",                                     "pt": "Temperatura",                                     "nl": "Temperatuur",                                     "fr": "Température",                                     "it": "Temperatura",                                     "es": "Temperatura",                                     "pl": "Temperatura",                                     "zh-cn": "温度"},
    "Type": {                                        "en": "Type",                                            "de": "Typ",                                             "ru": "Тип",                                             "pt": "Tipo",                                            "nl": "Type",                                            "fr": "Type",                                            "it": "genere",                                          "es": "Tipo",                                            "pl": "Rodzaj",                                          "zh-cn": "类型"},
    "Uptime:": {                                     "en": "Uptime",                                          "de": "Uptime",                                          "ru": "Uptime",                                          "pt": "Tempo de atividade",                              "nl": "Uptime",                                          "fr": "Temps de disponibilité",                          "it": "uptime",                                          "es": "Tiempo de actividad",                             "pl": "Czas pracy",                                      "zh-cn": "正常运行时间"},
    "WLAN:": {                                       "en": "WLAN",                                            "de": "WLAN",                                            "ru": "WLAN",                                            "pt": "WLAN",                                            "nl": "WLAN",                                            "fr": "WLAN",                                            "it": "WLAN",                                            "es": "WLAN",                                            "pl": "WLAN",                                            "zh-cn": "WLAN"},
    "in": {                                          "en": "in",                                              "de": "in",                                              "ru": "in",                                              "pt": "dentro",                                          "nl": "in",                                              "fr": "dans",                                            "it": "in",                                              "es": "en",                                              "pl": "w",                                               "zh-cn": "在"},
    "out": {                                         "en": "out",                                             "de": "out",                                             "ru": "out",                                             "pt": "Fora",                                            "nl": "uit",                                             "fr": "en dehors",                                       "it": "su",                                              "es": "fuera",                                           "pl": "na zewnątrz",                                     "zh-cn": "出来"},
};